### PR TITLE
add Windows support

### PR DESCRIPTION
**Pull request by gillins**
Add Windows support using the supplied `cscript` build system.

### CODE REVIEW

**Comment by gillins** [comment]
I haven't been able to regenerate, keep getting this error:

```
Fetching package metadata ............
Could not find URL: https://repo.continuum.io/pkgs/msys2/linux-64/
```

Is there a known good version of `conda-smithy`?

**Comment by gillins** [comment]
OK fixed by running `regenerate` on Linux. Weird...

**Comment by gillins** [comment]
I think AppVeyor may need to be restarted, seemed to stall building Python 2.7.

**Comment by ocefpaf** [comment]
> Is there a known good version of `conda-smithy`?

That is a known bug. See https://github.com/conda-forge/conda-smithy/issues/281

I will take a look at it this weekend but unfortunately `rerender` is broken on Windows.

**Comment by ocefpaf** [comment]
@msarahan and @patricksnape PY27 seems to be hanging at test time. Not sure what we should do on Windows to circumvent that :confused: 

``` shell
BUILD END: libxslt-1.1.29-vc9_1
TEST START: libxslt-1.1.29-vc9_1
WARNING: conda-build appears to be out of date. You have version 1.21.14 but the
latest version is 2.0.0. Run
conda update -n root conda-build
to get the latest version.
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    libxslt-1.1.29             |            vc9_1         325 KB  local
The following NEW packages will be INSTALLED:
    libiconv:       1.14-vc9_3     conda-forge [vc9]
    libxml2:        2.9.4-vc9_0    conda-forge [vc9]
    libxslt:        1.1.29-vc9_1   local       [vc9]
    python:         2.7.12-0       conda-forge
    vs2008_runtime: 9.00.30729.1-2 defaults   
    zlib:           1.2.8-vc9_3    conda-forge [vc9]
[conda] C:\conda\conda-bld\test-tmp_dir>call activate.bat C:\conda\envs\_test
```

**Comment by patricksnape** [comment]
If its hanging its probably because its throwing a modal dialog containing and error that it expects user interaction to dismiss. Let me check...

**Comment by patricksnape** [comment]
screenshot 2016-09-03 11 49 28

**Comment by patricksnape** [comment]
OK - so I think the problem is that libxml2 is linking against the system `MSVCR90.DLL` whereas the other libraries are linking against the `MSVCR90.DLL` from the conda Library directory.

**Comment by gillins** [comment]
Ah ha Thanks - now that you mention this I remember I had to insert a manifest with libxml2 which had a similar build system for reasons I never understood for py27. Will check tomorrow to see if this fixes it...

**Comment by patricksnape** [comment]
I tried the manifest trick from the libxml2 repo and it still crashed on my machine.

**Comment by gillins** [comment]
According to `depends.exe`, it is `libxml2` that is linked to the system `MSVCR90.DLL`, other DLLs are linked to Conda's `MSVCR90.DLL`. So maybe we have to revisit the `libxml2` recipe. Do you know how manifests work @patricksnape ? I couldn't work out why `libxml2` wouldn't work without a manifest in it.

**Comment by patricksnape** [comment]
In `libxml2.dll`:

```
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.VC90.CRT" version="9.0.21022.8" processorArchitecture="x86" publicKeyToken="1fc8b3b9a1e18e3b"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
</assembly>
```

Which references a specific release of the `MSVCR90.dll` which does not match the one we ship. So we definitely need to rebuild `libxml2.dll` but _without_ that manifest.

As a note, we ship `MSVCR90.dll` `9.00.30792.1`

**Comment by patricksnape** [comment]
The problem actually goes back to `libiconv` which embeds the Manifest.

**Comment by patricksnape** [comment]
Add even further back to `zlib`!

**Comment by patricksnape** [comment]
OK spent quite a lot of time debugging this to no avail. Tried rebuilding zlib, iconv and libxml2 with `/MANIFEST:NO` in order to force them to link against the conda shipped `msvcr90.dll`. My dependency walker now outputs:

capture

so we can see they are all linking against the same `msvcr90.dll`, but it **still** gives me the same error when running any of the built executables in the libxml2 recipe (R6034). None of the files contain a manifest as I grepped them for `dependency` and the manifests are definitely missing (whereas they were there before).

**Comment by patricksnape** [comment]
In fact, if I go through many of the libraries that we have been building, like `libpng` and `boost` they are linked against the `winsxs` `msvcr90.dll` and not the one supplied by conda...

**Comment by ocefpaf** [comment]
> In fact, if I go through many of the libraries that we have been building, like `libpng` and `boost` they are linked against the `winsxs` `msvcr90.dll` and not the one supplied by conda...

Sorry about my Windows ignorance but should we fix that? Or is it something that we can expect to exist on the end user computer?

**Comment by patricksnape** [comment]
OK - keeping with the maintaining of the Manifest - [this pr](https://github.com/gillins/libxslt-feedstock/pull/1) seems to fix building for me.

**Comment by patricksnape** [comment]
@ocefpaf Honestly this is a little over my head - I'm not even sure why Windows Python 2.7 builds are working on Windows machines without Visual Studio 2008 because the Manifest we build with contains a different version to the DLL version we ship with... so it should fail to resolve the DLL (from my understanding).

**Comment by gillins** [comment]
Maybe they just happen to work because people have the right libs installed from other software? Seems to be that we would get errors since some packages have a manifest and others not, but it is over my head too...

**Comment by ocefpaf** [comment]
> @ocefpaf Honestly this is a little over my head

Imagine mine :smile:

> I'm not even sure why Windows Python 2.7 builds are working on Windows machines without Visual Studio 2008 because the Manifest we build with contains a different version to the DLL version we ship with... so it should fail to resolve the DLL (from my understanding).

Maybe @msarahan can share some wisdom/experience with us. Many of the packages you mentioned were originally based on from `anaconda-recipes`.

Either way I cannot thank you and @gillins enough for tackling virtually all our Windows problems! I really own you guys some :beers:

**Comment by patricksnape** [comment]
Right well that worked... Let's pretend this never happened... 😆

**Comment by ocefpaf** [comment]
> Right well that worked... Let's pretend this never happened... 😆 

And I merged this just to pretend I did something :stuck_out_tongue_winking_eye:

**Pull request merged**
