### PR TITLE
Rebuild icu69 [manual]

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This is a manual duplicate of #23 that fixes the build issues.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@conda-forge/libxslt, this is ready for review, after which #23 can be closed.

**Review by mbargull — APPROVED** [review]
LGTM and thanks for having looked out for the missing linked libraries.!

**Comment by duncanmmacleod** [comment]
> LGTM and thanks for having looked out for the missing linked libraries.!

Because I'm compulsively pedantic, I alias `conda-build` to `conda build --error-overlinking --error-overdepending` on my machine, so I regularly trip over things like this. Happy to help.

**Comment by mbargull** [comment]
> > LGTM and thanks for having looked out for the missing linked libraries.!
> 
> Because I'm compulsively pedantic, I alias `conda-build` to `conda build --error-overlinking --error-overdepending` on my machine, so I regularly trip over things like this. Happy to help.

Well, Duncan, let me thank you again! For being so considerate and for putting a contented smile on my face with that :).

BTW, you can also put
```yaml
conda_build:
  error_overlinking: True
  error_overdepending: True
```
into your `.condarc` instead of using an alias (if you've added that, you should see it listed by `conda config --show-sources`).

**Pull request merged**
