### PR TITLE
Add dependency on icu

### LINKED ISSUE #8: Missing dependency on icu
See conda-forge/lxml-feedstock#10 for original report. From there, we can see:
```
$ objdump -p libxslt.so.1 | grep NEEDED
  NEEDED               libxml2.so.2
  NEEDED               libz.so.1
  NEEDED               liblzma.so.5
  NEEDED               libiconv.so.2
  NEEDED               libicui18n.so.58
  NEEDED               libicuuc.so.58
  NEEDED               libicudata.so.58
  NEEDED               libm.so.6
  NEEDED               libdl.so.2
  NEEDED               librt.so.1
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
$ objdump -p libexslt.so.0 | grep NEEDED
  NEEDED               libxslt.so.1
  NEEDED               libxml2.so.2
  NEEDED               libz.so.1
  NEEDED               liblzma.so.5
  NEEDED               libiconv.so.2
  NEEDED               libicui18n.so.58
  NEEDED               libicuuc.so.58
  NEEDED               libicudata.so.58
  NEEDED               libm.so.6
  NEEDED               libdl.so.2
  NEEDED               librt.so.1
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
```
which shows that libxslt requires libicu, but this is not in the build info. I guess the assumption is that it comes from libxml2, but since icu is a direct dependency, it should be required here as well.

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes #8.

I'm assuming the `[not win]` is correct. If not, I'll remove it.

### CODE REVIEW

**Comment by asmeurer** [comment]
For reference, run

```
conda create -n test libxslt icu=56
conda inspect linkages -n test libxslt
```

and it will show you that the linkages are broken for `icu`, because the versioning isn't included in the libxslt dependency (the conda install should have failed).

**Comment by ocefpaf** [comment]
In an ideal world the `libxml2` dependency on `icu` would suffice to make it present, but when people get `conda-forge`'s `libxslt` and `defaults` `libxml2` this does not happen :unamused: 

Let's merge this but in the long run we should pursue @QuLogic's ideas for a more permanent solution,

**Comment by ocefpaf** [comment]
@asmeurer BTW, if you let the channel preference work as expected everything is fine. See

```shell
> conda create --name TEST libxslt
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/filipe/miniconda3/envs/TEST:

The following NEW packages will be INSTALLED:

    icu:      58.1-1   conda-forge
    libiconv: 1.14-4   conda-forge
    libxml2:  2.9.4-4  conda-forge
    libxslt:  1.1.29-5 conda-forge
    xz:       5.2.2-0  conda-forge
    zlib:     1.2.11-0 conda-forge
```

The problem is that `conda` does not have a "conflicts with"  feature so we could forbid the installation of `icu 56`. Although, one would expect that, since `libxslt` depends on `libxml2` and the latter **is** complied with `icu 58.*` on conda-forge, one would never get `defaults` `libxml2` when using the channel preference feature, but that is clearly not the case for you there.

**Comment by asmeurer** [comment]
> The problem is that conda does not have a "conflicts with" feature so we could forbid the installation of icu 56. 

Yeah, you can use `ics >=58` or `icu !=56`. But the correct is is `58.*`, since that's the version of the dylib. 

> @asmeurer BTW, if you let the channel preference work as expected everything is fine. See

I disagree here. The library links against a versioned lib, so that should be reflected in the dependencies. Then conda will always do the right thing, because of its dependency solver. If it were an issue of "defaults icu 58 broken for some reason, but conda-forge icu 58 works", then I would agree, you should use conda-forge to fix it. But every package on conda-forge ought to have correct dependencies specified, so that conda can never install the wrong thing. For linked libraries, this means 1) if A links to B, then A should depend on B, and 2) if A links to a versioned B, then A should depend on the appropriate versions of B. 

Just depending on conda's default channel preferences is not as robust. As another use-case, consider if someone wants to build their own versions of some dependency (say, `icu`) in their own channel. Then say a newer version of icu comes out and they build it. Then conda will install it, and libxslt from conda-forge will break, because conda never knew about the versioned dependency.

**Pull request merged**
