### PR TITLE
Set and clear XML_CATALOG_FILES on activation and deactivation, respectively

### PR DESCRIPTION
**Pull request by hattne**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

This is needed to avoid manually setting `XML_CATALOG_FILES` wherever `xsltproc` is run. Compile-time defaults cannot be used, because the value of `XML_CATALOG_FILES` will depend on the name of the environment where it is installed.

Caveats:
* The Windows variables are set as per [User guide](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#saving-environment-variables); it's not clear to me how this will work under _e.g._ PowerShell
* `xmlcatalog` seems to do The Right Thing regardless of the presence of `XML_CATALOG_FILES`

### CODE REVIEW

**Comment by ocefpaf** [comment]
> * will work under _e.g._ PowerShell

You would probably need to create a .ps1 script to do the same. B/c we did not have any I'm OK merging this without out but before we do, do you want to try creating the PS1 scripts?

**Comment by hattne** [comment]
> > * will work under _e.g._ PowerShell
> 
> You would probably need to create a .ps1 script to do the same. B/c we did not have any I'm OK merging this without out but before we do, do you want to try creating the PS1 scripts?

OK, done. Thanks for pointing me to the `ps1` files!

But… since `xmlcatalog`—and catalog management in general—is provided by [`libxml2`](https://github.com/conda-forge/libxml2-feedstock) and not this package, I'm thinking this patch may be more suitable there. Opinions?

**Comment by ocefpaf** [comment]
> But… since `xmlcatalog`—and catalog management in general—is provided by [`libxml2`](https://github.com/conda-forge/libxml2-feedstock) and not this package, I'm thinking this patch may be more suitable there. Opinions?

Yep. It belongs there then.

**Comment by hattne** [comment]
> > But… since `xmlcatalog`—and catalog management in general—is provided by [`libxml2`](https://github.com/conda-forge/libxml2-feedstock) and not this package, I'm thinking this patch may be more suitable there. Opinions?
> 
> Yep. It belongs there then.

OK, I'll close this PR once https://github.com/conda-forge/libxml2-feedstock/pull/82 has been resolved.

**Comment by celestino-amado** [comment]
This changes are causing an issue on Windows OS: the Anaconda Prompt (cmd) started behaving not as expected when lauching and after using conda commands. 

To fix it:
- just need to change recipe/activate.bat to start lines 1 and 2 with @
(use @set instead of set) 
- and change recipe/desactivate.bat to start lines 1, 2, 4 and 6 with @
(use @if instead of if and use @set instead of set)

**Pull request closed without merging**
